# Generated by Django 6.0.5 on 2026-10-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pusinex", "0008_manzana_geom_alter_actualizacionmge_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroArt141",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciudadano_id", models.CharField(db_index=True, max_length=100)),
                ("fecha_solicitud_afectacion", models.DateField(blank=True, null=True)),
                ("edad", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sexo", models.CharField(blank=True, default="", max_length=20)),
                (
                    "folio_nacional",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("lista_nominal", models.BooleanField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "manzana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_art141",
                        to="pusinex.manzana",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_art141",
                        to="pusinex.seccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Artículo 141",
                "verbose_name_plural": "Registros Artículo 141",
                "ordering": [
                    "seccion__distrito__distrito",
                    "seccion__municipio__municipio",
                    "seccion__seccion",
                    "manzana__localidad",
                    "manzana__manzana",
                ],
            },
        ),
    ]
