# Generated by Django 6.0.5 on 2026-10-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art141", "0001_initial"),
        ("pusinex", "0008_manzana_geom_alter_actualizacionmge_tipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registroart141",
            options={
                "verbose_name": "Registro Artículo 141",
                "verbose_name_plural": "Registros Artículo 141",
            },
        ),
        migrations.AddField(
            model_name="registroart141",
            name="distrito",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroart141",
            name="entidad",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroart141",
            name="localidad",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroart141",
            name="manzana_origen",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroart141",
            name="municipio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registroart141",
            name="seccion_origen",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registroart141",
            name="manzana",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_art141",
                to="pusinex.manzana",
            ),
        ),
        migrations.AlterField(
            model_name="registroart141",
            name="seccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_art141",
                to="pusinex.seccion",
            ),
        ),
    ]
