# Generated by Django 6.0.5 on 2026-10-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "art141",
            "0002_alter_registroart141_options_registroart141_distrito_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registroart141",
            options={
                "ordering": ["fecha_solicitud_tramite", "fuar"],
                "verbose_name": "Registro Artículo 141",
                "verbose_name_plural": "Registros Artículo 141",
            },
        ),
        migrations.RemoveField(
            model_name="registroart141",
            name="fecha_solicitud_afectacion",
        ),
        migrations.RemoveField(
            model_name="registroart141",
            name="folio_nacional",
        ),
        migrations.RemoveField(
            model_name="registroart141",
            name="lista_nominal",
        ),
        migrations.AddField(
            model_name="registroart141",
            name="estatusciudadano_id",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroart141",
            name="fecha_entrega_credencial",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroart141",
            name="fecha_solicitud_tramite",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroart141",
            name="fuar",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
