# Generated by Django 6.0.5 on 2026-10-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art141", "0003_alter_registroart141_options_and_more"),
        ("pusinex", "0008_manzana_geom_alter_actualizacionmge_tipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registroart141",
            options={},
        ),
        migrations.AddConstraint(
            model_name="registroart141",
            constraint=models.UniqueConstraint(
                fields=("ciudadano_id", "fecha_solicitud_tramite"),
                name="uniq_art141_ciudadano_fecha",
            ),
        ),
    ]
