# Generated by Django 6.0.5 on 2026-07-14 18:55

import apps.pusinex.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "entidad",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.TextField()),
                ("circunscripcion", models.PositiveSmallIntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=32614
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entidades",
                "ordering": ["entidad"],
            },
        ),
        migrations.CreateModel(
            name="DistritoLocal",
            fields=[
                (
                    "distrito_local",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("cabecera", models.TextField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=32614
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.entidad",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Distritos Locales",
                "ordering": ["entidad", "distrito_local"],
            },
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "distrito",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("tipo", models.PositiveSmallIntegerField()),
                ("cabecera", models.TextField()),
                (
                    "ubica",
                    models.TextField(
                        default="", help_text="Coordinadas de la ubicación del distrito"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=32614
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.entidad",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Distritos",
                "ordering": ["entidad", "distrito"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "municipio",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.TextField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=32614
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.entidad",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Municipios",
                "ordering": ["entidad", "municipio"],
            },
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "seccion",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "tipo",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "URBANO CONCENTRADO"),
                            (2, "URBANO(A)"),
                            (3, "MIXTO"),
                            (4, "RURAL"),
                            (5, "RURAL DISPERSO"),
                        ]
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=32614
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.distrito",
                    ),
                ),
                (
                    "distrito_l",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.distritolocal",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.entidad",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.municipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["distrito__distrito", "municipio__municipio", "seccion"],
            },
        ),
        migrations.CreateModel(
            name="Pusinex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_act", models.DateField()),
                ("hojas", models.PositiveSmallIntegerField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.pusinex.models.pusinex_file,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.seccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "PUSINEX",
                "verbose_name_plural": "PUSINEXs",
                "ordering": [
                    "seccion__distrito__distrito",
                    "seccion__municipio__municipio",
                    "seccion__seccion",
                ],
                "get_latest_by": ["f_act"],
            },
        ),
    ]
