# Generated by Django 6.0.5 on 2026-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seccion",
            name="distrito_l",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
