# Generated by Django 6.0.5 on 2026-07-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="distrito",
            name="distancia",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distrito",
            name="traslado",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tiempo de traslado al distrito en minutos",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entidad",
            name="ubica",
            field=models.TextField(
                default="", help_text="Coordenadas geográficas de la Junta Local"
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="distancia",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seccion",
            name="traslado",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tiempo de traslado a la sección en minutos",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="ubica",
            field=models.TextField(
                default="", help_text="Coordinadas de la ubicación de la sección"
            ),
        ),
    ]
