# Generated by Django 6.0.5 on 2026-07-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0002_distrito_distancia_distrito_traslado_entidad_ubica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.PositiveSmallIntegerField()),
                ('manzana', models.PositiveSmallIntegerField()),
                ('padron', models.PositiveIntegerField(default=0)),
                ('lista_nominal', models.PositiveIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manzanas', to='pusinex.seccion')),
            ],
            options={
                'verbose_name': 'Manzana',
                'verbose_name_plural': 'Manzanas',
                'ordering': ['seccion', 'localidad', 'manzana'],
                'unique_together': {('seccion', 'localidad', 'manzana')},
            },
        ),
    ]
