# Generated by Django 6.0.5 on 2026-06-05 15:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0002_seccion_distrito_l"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipio",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=32614
            ),
        ),
        migrations.CreateModel(
            name="DistritoLocal",
            fields=[
                (
                    "distrito_local",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("cabecera", models.TextField()),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pusinex.entidad",
                    ),
                ),
            ],
        ),
    ]
