# Generated by Django 6.0.5 on 2026-07-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0003_manzana"),
    ]

    operations = [
        migrations.AddField(
            model_name="distrito",
            name="ln",
            field=models.PositiveIntegerField(
                default=0, help_text="Lista Nominal precalculada"
            ),
        ),
        migrations.AddField(
            model_name="distrito",
            name="pe",
            field=models.PositiveIntegerField(
                default=0, help_text="Padrón Electoral precalculado"
            ),
        ),
        migrations.AddField(
            model_name="entidad",
            name="ln",
            field=models.PositiveIntegerField(
                default=0, help_text="Lista Nominal precalculada"
            ),
        ),
        migrations.AddField(
            model_name="entidad",
            name="pe",
            field=models.PositiveIntegerField(
                default=0, help_text="Padrón Electoral precalculado"
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="ln",
            field=models.PositiveIntegerField(
                default=0, help_text="Lista Nominal precalculada"
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="pe",
            field=models.PositiveIntegerField(
                default=0, help_text="Padrón Electoral precalculado"
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="ln",
            field=models.PositiveIntegerField(
                default=0, help_text="Lista Nominal precalculada"
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="pe",
            field=models.PositiveIntegerField(
                default=0, help_text="Padrón Electoral precalculado"
            ),
        ),
    ]
