# Generated by Django 6.0.5 on 2026-06-05 16:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0003_municipio_geom_distritolocal"),
    ]

    operations = [
        migrations.AddField(
            model_name="entidad",
            name="circunscripcion",
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entidad",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=32614
            ),
        ),
    ]
