# Generated by Django 6.0.5 on 2026-06-05 17:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0004_entidad_circunscripcion_entidad_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32614),
        ),
        migrations.AddField(
            model_name='distritolocal',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32614),
        ),
    ]
