# Generated by Django 6.0.5 on 2026-07-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0004_distrito_ln_distrito_pe_entidad_ln_entidad_pe_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pusinex",
            options={
                "get_latest_by": ["f_act"],
                "ordering": [
                    "seccion__distrito__distrito",
                    "seccion__municipio__municipio",
                    "seccion__seccion",
                ],
                "permissions": [
                    ("generate_pusinex_packages", "Puede generar paquetes PUSINEX")
                ],
                "verbose_name": "PUSINEX",
                "verbose_name_plural": "PUSINEXs",
            },
        ),
    ]
