# Generated by Django 6.0.5 on 2026-10-02 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0005_alter_pusinex_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="entidad",
            name="circunscripcion",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.CreateModel(
            name="ActualizacionMGE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "Diagnóstico"),
                            ("ACTUALIZACION", "Actualización"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INICIADA", "Iniciada"),
                            ("APTO", "Apto"),
                            ("NO_APTO", "No apto"),
                            ("COMPLETADA", "Completada"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor", models.CharField(max_length=150)),
                ("origen", models.TextField()),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                ("reporte", models.JSONField(blank=True, default=dict)),
                ("mensaje_error", models.TextField(blank=True, default="")),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualización MGE",
                "verbose_name_plural": "Actualizaciones MGE",
                "ordering": ["-inicio"],
            },
        ),
    ]
