# Generated by Django 6.0.5 on 2026-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0005_distrito_geom_distritolocal_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='tipo',
            field=models.PositiveSmallIntegerField(default=9),
            preserve_default=False,
        ),
    ]
