# Generated by Django 6.1.1 on 2026-10-02 22:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0006_alter_entidad_circunscripcion_actualizacionmge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioMGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('GEOMETRIA', 'Geometría'), ('ALTA', 'Alta'), ('BAJA', 'Baja')], max_length=20)),
                ('geom_anterior', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32614)),
                ('geom_nueva', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32614)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='pusinex.actualizacionmge')),
            ],
            options={
                'verbose_name': 'Cambio MGE',
                'verbose_name_plural': 'Cambios MGE',
                'ordering': ['-creado'],
            },
        ),
    ]
