# Generated by Django 6.0.5 on 2026-06-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0006_distrito_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='distritolocal',
            options={'verbose_name_plural': 'Distritos Locales'},
        ),
    ]
