# Generated by Django 6.1.1 on 2026-10-03 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0007_cambiomge'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzana',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32614),
        ),
        migrations.AlterField(
            model_name='actualizacionmge',
            name='tipo',
            field=models.CharField(choices=[('GEOMETRIA', 'Geometría'), ('ALTA', 'Alta'), ('BAJA', 'Baja'), ('REACTIVACION', 'Reactivación')], max_length=20),
        ),
    ]
