# Generated by Django 6.0.5 on 2026-06-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0007_alter_distrito_options_alter_distritolocal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['entidad', 'distrito'], 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='distritolocal',
            options={'ordering': ['entidad', 'distrito_local'], 'verbose_name_plural': 'Distritos Locales'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['entidad'], 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['entidad', 'municipio'], 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AddField(
            model_name='seccion',
            name='entidad',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='pusinex.entidad'),
            preserve_default=False,
        ),
    ]
