# Generated by Django 6.0.5 on 2026-06-05 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0008_alter_distrito_options_alter_distritolocal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='distrito_l',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pusinex.distritolocal'),
            preserve_default=False,
        ),
    ]
