# Generated by Django 6.0.5 on 2026-10-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0008_entidad_fecha_corte_pe_ln_distritolocal_ln_and_more"),
        ("pusinex", "0008_manzana_geom_alter_actualizacionmge_tipo"),
    ]

    operations = []
