# Generated by Django 6.0.5 on 2026-06-05 18:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pusinex', '0009_alter_seccion_distrito_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32614),
        ),
    ]
