# Generated by Django 6.0.5 on 2026-10-07 18:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0009_merge_20261007_1051"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localidad", models.PositiveSmallIntegerField()),
                ("nombre", models.TextField()),
                ("tipo", models.PositiveSmallIntegerField()),
                ("cabecera", models.PositiveSmallIntegerField()),
                ("status", models.PositiveSmallIntegerField()),
                ("control", models.PositiveIntegerField()),
                ("id_bgd", models.PositiveIntegerField(unique=True)),
                (
                    "padron",
                    models.PositiveIntegerField(
                        default=0, help_text="Padrón Electoral"
                    ),
                ),
                (
                    "lista_nominal",
                    models.PositiveIntegerField(default=0, help_text="Lista Nominal"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=32614
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localidades",
                        to="pusinex.seccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localidad Puntual",
                "verbose_name_plural": "Localidades Puntuales",
                "ordering": ["seccion", "localidad"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seccion", "localidad"), name="unique_seccion_localidad"
                    )
                ],
            },
        ),
    ]
