# Generated by Django 6.0.5 on 2026-10-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pusinex", "0010_localidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="PelnResidualSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_corte", models.DateField()),
                ("localidad", models.PositiveSmallIntegerField()),
                ("manzana", models.PositiveSmallIntegerField()),
                (
                    "padron",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Padrón Electoral sin georreferencia precisa",
                    ),
                ),
                (
                    "lista_nominal",
                    models.PositiveIntegerField(
                        default=0, help_text="Lista Nominal sin georreferencia precisa"
                    ),
                ),
                ("edmslm", models.CharField(max_length=19)),
                ("motivo", models.CharField(max_length=50)),
                ("archivo", models.TextField(blank=True, default="")),
                ("fila", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peln_residuales",
                        to="pusinex.seccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "PE/LN residual de sección",
                "verbose_name_plural": "PE/LN residuales de sección",
                "ordering": ["seccion", "localidad", "manzana"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fecha_corte", "edmslm"),
                        name="unique_peln_residual_corte_edmslm",
                    )
                ],
            },
        ),
    ]
