# Generated by Django 5.0.6 on 2024-11-01 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pos', models.IntegerField(help_text='Posición u orden del Indicador', verbose_name='Posición')),
                ('type', models.IntegerField(choices=[(1, 'Objetivo'), (2, 'Indicador')], help_text='Indica si es una Objetivo o un KPI', verbose_name='Tipo')),
                ('name', models.CharField(help_text='Nombre del Objetivo o Indicador', max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción detallada del Objetivo o Indicador', verbose_name='Descripción')),
                ('formula', models.TextField(verbose_name='Fórmula')),
                ('lapse', models.IntegerField(choices=[(1, 'Semanal'), (1, 'Remesa'), (3, 'Mensual'), (4, 'Bimestral'), (5, 'Trimestral'), (6, 'Cuatrimestral'), (7, 'Semestral'), (8, 'Anual'), (9, 'Por campaña'), (10, 'Por campaña/remesa'), (11, 'Por campaña/mensual'), (12, 'Por campaña/semanal')], default=3, help_text='Periodo de medición', verbose_name='Medición')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Descripción o nombre del periodo de tiempo', max_length=255, verbose_name='Periodo')),
                ('start', models.DateField(help_text='Fecha de inicio del periodo', verbose_name='Inicio')),
                ('end', models.DateField(help_text='Fecha de fin del periodo', verbose_name='Fin')),
                ('target', models.FloatField(verbose_name='Meta')),
                ('nominal', models.FloatField(verbose_name='Nominativo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpi')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ('kpi', 'period'),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('cumulative_value', models.FloatField(default=0, editable=False, verbose_name='Valor Acumulado')),
                ('percentage_of_nominal', models.FloatField(default=0, editable=False, verbose_name='Porcentaje del Nominal')),
                ('cumulative_percentage', models.FloatField(default=0, editable=False, verbose_name='Porcentaje Acumulado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ('period__kpi', 'date'),
            },
        ),
    ]
