# Generated by Django 5.1.2 on 2024-11-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi',
            old_name='type',
            new_name='kpi_type',
        ),
    ]
