# Generated by Django 6.0.5 on 2026-07-20 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cecyrd", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionDireccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text="Identificador único del semestre, ej. 'sem1_2026'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("fecha_cierre", models.DateTimeField(auto_now_add=True)),
                ("total_tramites", models.PositiveIntegerField(default=0)),
                ("analizados", models.PositiveIntegerField(default=0)),
                ("en_tiempo", models.PositiveIntegerField(default=0)),
                ("rezago", models.PositiveIntegerField(default=0)),
                ("porcentaje_global", models.FloatField(default=0.0)),
                ("promedio_dias", models.FloatField(default=0.0)),
                (
                    "conclusiones",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones analíticas del responsable",
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Acciones correctivas o de mejora continua",
                    ),
                ),
                (
                    "pdf_oficial",
                    models.FileField(
                        blank=True,
                        help_text="Fotografía institucional inmutable del periodo generada post-ETL",
                        null=True,
                        upload_to="cecyrd/portadas/",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que generó el cierre inicial",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisión por la Dirección",
                "verbose_name_plural": "Revisiones por la Dirección",
                "ordering": ["-fecha_cierre"],
            },
        ),
    ]
